### PR TITLE
Refactor to 2.0.0

### PR DESCRIPTION
**Pull request by miketheman**
Hello @owynrichen !

We've started to use pgbouncer in a heavy way, and @DorianZaccaria did an awesome test/spec suite to cover the current behaviors, and then refactored a bunch to incorporate some good practices of allowing arbitrary attribute inclusion from @boldfield, and then further replaced the current `connection` LWRP  with `instance` to allow for multiple db alias entries in a single pgbouncer running instance.

This is likely to move the cookbook to version 2.0.0, as the LWRP has been renamed, the templates have been cleaned up a ton, and there's likely unexpected behavior to anyone currently using the cookbook.

We're hoping you'll merge this in, and release to the supermarket - there's likely some README updates to follow.
If you're looking to add maintainers, then I think this might be a good opportunity to help share the load.

### CODE REVIEW

**Comment by owynrichen** [comment]
Hey @miketheman, this repository is owned by members of a company I'm no longer with, so I don't have merge access to the repository anymore.  I might check with @jfoy, @dbenhur, @svend or another person who probably still does :).  Thanks for the contribution in any event!

**Comment by miketheman** [comment]
Ping for @jfoy @dbenhur @svend

**Comment by irvingpop** [comment]
Hey @owynrichen - would you be open to putting this cookbook [up for adoption in Supermarket](https://www.chef.io/blog/2014/12/04/adopt-a-cookbook/) ?

**Comment by miketheman** [comment]
Closing, due to inactivity. This is definitely something that should be put up for adoption, or figure out who active maintainers might be.

**Pull request closed without merging**
